import unittest
from unittest.mock import MagicMock
from graphsitegen.htmlutils import HtmlGenerator
from graphsitegen.filesystem.filemanager import FileManager
from graphsitegen.article import Article
import os

class TestHtmlGenerator:
    def setup_method(self, method):
        current = os.path.dirname(os.path.realpath(__file__))
        templates = os.path.join(current, 'test_data/templates')
        self.filemgr = FileManager('input', 'output', templates)
        self.filemgr.save_output = MagicMock()
        self.gen = HtmlGenerator(self.filemgr)

    def test_WithValidTemplate_WhenGenerateArticle_ThenGeneratesCorrectArticle(self):
        self.gen.generate_article(Article('title', [], [], '2020-01-01', 'abstract', 'content'), '')
        self.filemgr.save_output.assert_called_with(unittest.mock.ANY, '<!DOCTYPE html>\n<html lang="en">\n<title>title</title>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">\n<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Quicksand:wght@300">\n<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">\n<style>\nbody {font-family: "Quicksand", sans-serif; font-size: 15pt;}\n.mySlides {display: none}\n.logoBg {\n    background-image: url("images/logo/logo32.png");\n    background-repeat: no-repeat;\n    background-position: center;\n    background-size: 40px;\n    width: 100%;\n  }\n</style>\n<body>\n\n<!-- NavBar -->\n<div class="w3-top">\n  <div class="w3-bar w3-black w3-card logoBg">\n    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>\n    <a href="index.html" class="w3-bar-item w3-button w3-padding-large">HOME</a>\n    <a href="map.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">BLOG</a>\n  </div>\n</div>\n\n<!-- Navbar on small screens (remove the onclick attribute if you want the navbar to always show on top of the content when clicking on the links) -->\n<!-- <div id="navDemo" class="w3-bar-block w3-black w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:46px">\n  <a href="#band" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">BAND</a>\n  <a href="#tour" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">TOUR</a>\n  <a href="#contact" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">CONTACT</a>\n  <a href="#" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">MERCH</a>\n</div> -->\n\n<!-- Page content -->\n<div class="w3-content" style="max-width:2000px;margin-top:46px">\n\n\t<!-- The Graph Section -->\n  <div id="tour">\n    <div class="w3-padding-64 w3-center">\n      \n    </div>\n  </div>\n\n  <!-- The Content Section -->\n  <div class="w3-light-grey">\n\t  <div class="w3-content w3-padding-64" id="band">\n\t    <p>content</p>\n\t  </div>\n  </div>\n\n</body>\n</html>\n')

    def test_WithValidTemplate_WhenGenerateMap_ThenGeneratesCorrectMap(self):
        self.gen.generate_map('')
        self.filemgr.save_output.assert_called_with(unittest.mock.ANY, '<!DOCTYPE html>\n<html lang="en">\n<title>Graph</title>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">\n<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Quicksand:wght@300">\n<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">\n<style>\nbody {font-family: "Quicksand", sans-serif; font-size: 15pt;}\n.mySlides {display: none}\n.logoBg {\n    background-image: url("images/logo/logo32.png");\n    background-repeat: no-repeat;\n    background-position: center;\n    background-size: 40px;\n    width: 100%;\n  }\n</style>\n<body>\n\n<!-- Navbar -->\n<div class="w3-top">\n  <div class="w3-bar w3-black w3-card logoBg">\n    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>\n    <a href="index.html" class="w3-bar-item w3-button w3-padding-large">HOME</a>\n    <a href="map.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">BLOG</a>\n  </div>\n</div>\n\n<!-- Navbar on small screens (remove the onclick attribute if you want the navbar to always show on top of the content when clicking on the links) -->\n<!-- <div id="navDemo" class="w3-bar-block w3-black w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:46px">\n  <a href="#band" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">BAND</a>\n  <a href="#tour" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">TOUR</a>\n  <a href="#contact" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">CONTACT</a>\n  <a href="#" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">MERCH</a>\n</div> -->\n\n<!-- Page content -->\n<div class="w3-content" style="max-width:2000px;margin-top:46px">\n\n  <div class="w3-light-gray">\n    <div class="w3-container w3-content w3-padding-32">\n      <h1>This is the complete map of articles</h1>\n      <h2>Most recent articles</h2>\n      <p>Read the most recent articles <a href="news.html">here</a>.</p>\n    </div>\n  </div>\n\n  <!-- The Graph Section -->\n  <div id="tour" style="overflow-x: scroll;">\n    <div class="w3-container w3-content w3-padding-32">\n      \n    </div>\n  </div>\n\n</body>\n</html>\n')

    def test_WithValidTemplate_WhenGenerateNews_ThenGeneratesCorrectNews(self):
        self.gen.generate_news('')
        self.filemgr.save_output.assert_called_with(unittest.mock.ANY, '<!DOCTYPE html>\n<html lang="en">\n<title>What\'s new</title>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">\n<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Quicksand:wght@300">\n<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">\n<style>\nbody {font-family: "Quicksand", sans-serif; font-size: 15pt;}\n.mySlides {display: none}\n.logoBg {\n    background-image: url("images/logo/logo32.png");\n    background-repeat: no-repeat;\n    background-position: center;\n    background-size: 40px;\n    width: 100%;\n  }\n</style>\n<body>\n\n<!-- Navbar -->\n<div class="w3-top">\n  <div class="w3-bar w3-black w3-card logoBg">\n    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>\n    <a href="index.html" class="w3-bar-item w3-button w3-padding-large">HOME</a>\n    <a href="map.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">BLOG</a>\n  </div>\n</div>\n\n<!-- Navbar on small screens (remove the onclick attribute if you want the navbar to always show on top of the content when clicking on the links) -->\n<!-- <div id="navDemo" class="w3-bar-block w3-black w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:46px">\n  <a href="#band" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">BAND</a>\n  <a href="#tour" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">TOUR</a>\n  <a href="#contact" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">CONTACT</a>\n  <a href="#" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">MERCH</a>\n</div> -->\n\n<!-- Page content -->\n<div class="w3-content" style="max-width:2000px;margin-top:46px">\n\n  <div class="w3-light-gray">\n    <div class="w3-container w3-content w3-padding-32">\n      <h1>What\'s new</h1>\n      <p>\n        Below is the list of the most recent articles. <br/>\n        There are 0 articles.\n      </p>\n      \n    </div>\n  </div>\n\n</body>\n</html>\n')